[package]
name = "lure"
description = "Display your currently playing track from Last.fm, ListenBrainz, and other services in your Revolt status!"
authors = ["tuhana <tuhana.cat+git@gmail.com>"]
version = "0.4.0"
rust-version = "1.80"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive"] }
figment = { version = "0.10.19", features = ["env", "yaml"] }
inquire = { version = "0.7.5", default-features = false, features = ["crossterm"] }
regex = "1.10.6"
serde = { version = "1.0.204", features = ["derive"] }

[features]
default = ["services_lastfm", "services_listenbrainz"]
services_lastfm = []
services_listenbrainz = []
