[package]
name = "lure"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
clap = { version = "4.4.5", features = ["derive", "env"] }
reqwest = { version = "0.11.20", features = ["json"] }
rive-http = { git = "https://codeberg.org/rive/rive", rev = "f49f7c6" }
rive-models = { git = "https://codeberg.org/rive/rive", rev = "f49f7c6" }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = [
  "macros",
  "rt-multi-thread",
  "time",
  "sync",
  "signal",
] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[features]
default = ["lastfm", "listenbrainz"]
lastfm = []
listenbrainz = []
