[package]
name = "lure"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
clap = { version = "4.4.7", features = ["derive"] }
confique = { git = "https://github.com/tuhanayim/confique", rev = "2c85724", default-features = false, features = [
  "toml",
] }
dirs = "5.0.1"
reqwest = { version = "0.11.22", features = ["json"] }
rive-http = { git = "https://codeberg.org/rive/rive", rev = "f49f7c6" }
rive-models = { git = "https://codeberg.org/rive/rive", rev = "f49f7c6" }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.33.0", features = [
  "fs",
  "macros",
  "rt-multi-thread",
  "time",
  "sync",
  "signal",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[features]
default = ["lastfm", "listenbrainz"]
lastfm = []
listenbrainz = []
