[package]
name = "lure"
description = "Display your currently playing track from Last.fm, ListenBrainz, and other services in your Revolt status!"
repository = "https://github.com/catuhana/lure"
authors = ["tuhana <tuhana.cat+git@gmail.com>"]
version = "0.4.0"
rust-version = "1.80"
edition = "2021"

[profile.release]
opt-level = "z"
lto = "fat"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.14", features = ["derive"] }
figment = { version = "0.10.19", features = ["env", "yaml"], optional = true }
figment_file_provider_adapter = "0.1.1"
inquire = { version = "0.7.5", default-features = false, features = [
  "crossterm",
] }
regex = "1.10.6"
reqwest = { version = "0.12.5", features = ["json"] }
rive-models = "1.2.1"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
tokio = { version = "1.39.2", features = ["rt-multi-thread", "macros"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[features]
default = ["services-lastfm", "services-listenbrainz"]
services-lastfm = ["dep:figment", "tokio/sync", "tokio/signal", "tokio/time"]
services-listenbrainz = [
  "dep:figment",
  "tokio/sync",
  "tokio/signal",
  "tokio/time",
]
