[package]
name = "lure"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.12", features = ["derive"] }
confique = { git = "https://github.com/catuhana/confique", rev = "2c85724", default-features = false, features = [
  "toml",
] }
dirs = "5.0.1"
reqwest = { version = "0.11.23", features = ["json"] }
rive-http = { git = "https://codeberg.org/rive/rive", rev = "0c2f126" }
rive-models = { git = "https://codeberg.org/rive/rive", rev = "0c2f126" }
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.109"
tokio = { version = "1.35.1", features = [
  "fs",
  "macros",
  "rt-multi-thread",
  "time",
  "sync",
  "signal",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[features]
default = ["lastfm", "listenbrainz"]
lastfm = []
listenbrainz = []
