name: Build Code

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runs on
        type: string
        required: true

jobs:
  build-nix:
    name: Build Code via Nix
    if: inputs.runs-on != 'windows-latest'
    runs-on: ${{ inputs.runs-on }}
    permissions:
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build project
        run: nix build

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v7
        with:
          name: lure-${{ runner.os }}
          path: result/bin/lure

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: lure-${{ runner.os }}
          subject-digest: sha256:${{ steps.upload-artifact.outputs.artifact-digest }}

  build-cargo:
    name: Build Code via Cargo
    if: inputs.runs-on == 'windows-latest'
    runs-on: ${{ inputs.runs-on }}
    permissions:
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Rust toolchain
        run: rustup toolchain install

      - name: Set up Rust cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Build project
        run: cargo build --release

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v7
        with:
          name: lure-${{ runner.os }}
          path: target/release/lure.exe

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v4
        with:
          subject-name: lure-${{ runner.os }}
          subject-digest: sha256:${{ steps.upload-artifact.outputs.artifact-digest }}
