name: CD
run-name: ${{ inputs.reason }}

on:
  push:
    tags:
      - v*
  workflow_run:
    workflows:
      - CI
    types:
      - completed
  workflow_dispatch:
    inputs:
      reason:
        description: Dispatch reason
        required: true
        type: string

jobs:
  build-and-upload:
    uses: ./.github/workflows/build-code.yaml
    if: |
      github.event_name != 'workflow_run' ||
        (github.event_name == 'workflow_run' &&
          github.event.workflow_run.conclusion == 'success')
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    with:
      runs-on: ${{ matrix.os }}
  push-container-image:
    name: Push Container Image
    uses: ./.github/workflows/docker-push.yaml
    if: |
      github.event_name != 'workflow_run' ||
        (github.event_name == 'workflow_run' &&
          github.event.workflow_run.conclusion == 'success')
    with:
      image-name: lure
