name: CI
run-name: ${{ inputs.reason }}

on:
  push:
    paths:
      - .github/workflows/ci.yaml
      - .github/workflows/code-check.yaml
      - lure-*/**
      - build.rs
      - Cargo.lock
      - Cargo.toml
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/ci.yaml
      - .github/workflows/code-check.yaml
      - lure-*/**
      - build.rs
      - Cargo.lock
      - Cargo.toml
  workflow_dispatch:
    inputs:
      reason:
        description: Dispatch reason
        type: string
        required: true

jobs:
  code-check:
    uses: ./.github/workflows/code-check.yaml
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        rust-toolchain:
          - stable
          - nightly
    with:
      runs-on: ${{ matrix.os }}
      rust-toolchain: ${{ matrix.rust-toolchain }}
