name: Check Code

on:
  workflow_call:

jobs:
  check:
    name: Check Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run flake checks
        run: nix flake check
