name: Check Code, Code Formatting and Linting

on:
  workflow_call:
    inputs:
      runs-on:
        description: Runs on
        default: ubuntu-latest
        type: string
      rust-toolchain:
        description: Rust toolchain
        default: stable
        type: string

jobs:
  tests:
    name: Check Code, Code Formatting and Linting
    runs-on: ${{ inputs.runs-on }}
    env:
      CARGO_TERM_COLOR: always
      CARGO_TERM_VERBOSE: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/check-rust-input-parameters
        with:
          runs-on: ${{ inputs.runs-on }}
          rust-toolchain: ${{ inputs.rust-toolchain }}

      - name: Set-up Rust problem matchers
        uses: catuhana/rust-problem-matchers@v2

      - name: Set-up or update Rust ${{ inputs.rust-toolchain }} toolchain
        run: rustup toolchain install ${{ inputs.rust-toolchain }} --profile default

      - name: Set-up Rust cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            target/
          key: ${{ runner.os }}-cargo-${{ inputs.rust-toolchain }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-hack
        run: cargo install cargo-hack

      - name: Check Rust code
        run: cargo +${{ inputs.rust-toolchain }} hack --each-feature check

      - name: Check Rust code format
        # prettier-ignore
        if: '!cancelled()'
        run: cargo +${{ inputs.rust-toolchain }} hack --each-feature fmt --all --check

      - name: Check Rust code lint
        # prettier-ignore
        if: '!cancelled()'
        run: cargo +${{ inputs.rust-toolchain }} hack --each-feature clippy
