name: Push to GitHub Container Registry

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string

jobs:
  push-container-image:
    name: Push Container Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set-up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set-up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata for container image
        uses: docker/metadata-action@v5
        id: container-metadata
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=edge
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Build and publish container image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.docker-platform }}
          push: true
          file: Containerfile
          tags: ${{ steps.container-metadata.outputs.tags }}
          labels: ${{ steps.container-metadata.outputs.labels }}
