name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  check-release-conditions:
    name: Check Release Conditions
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == github.base_ref &&
      startsWith(github.event.pull_request.head.ref, 'release/v') &&
      startsWith(github.event.pull_request.title, 'Bump version to')
    steps:
      - run: echo ::set-output name=result::success
  build-and-upload-artifact:
    name: Build and Upload Artifact
    uses: ./.github/workflows/build-code.yaml
    needs: check-release-conditions
    if: ${{ needs.check-release-conditions.result == 'success' }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    with:
      runs-on: ${{ matrix.os }}
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-and-upload-artifact
    if: ${{ needs.build-and-upload-artifact.result == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: target/release/lure-cli*

      - name: Create release and upload assets
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          BRANCH_NAME=$(echo ${{ github.event.pull_request.head.ref }})
          RELEASE_TAG=$(echo ${BRANCH_NAME#*/})

          gh release create "$RELEASE_TAG" --title "Release $RELEASE_TAG" --generate-notes
          gh release upload "$RELEASE_TAG" target/release/lure-cli*
  push-container-image:
    name: Push Container Image
    uses: ./.github/workflows/docker-push.yaml
    needs: check-release-conditions
    if: ${{ needs.check-release-conditions.result == 'success' }}
    with:
      image-name: lure
