name: Release
run-name: ${{ inputs.reason }}

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      reason:
        description: Dispatch reason
        required: true
        type: string

jobs:
  create-release:
    name: Create Release
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release-upload-url: ${{ steps.create-release.outputs.result }}
    steps:
      - name: Create release
        id: create-release
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.ref.split('/').at(-1);
            const release = await github.rest.repos.createRelease({
              name: `Release ${tag}`,
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tag,
              generate_release_notes: true
            });

            return release.data.upload_url;

  build-and-upload:
    name: Build and Upload
    needs: create-release
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup or update Rust toolchain
        run: rustup toolchain install stable --profile default

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build project
        run: cargo build --verbose --release

      - name: Upload Release Asset
        uses: actions/github-script@v7
        with:
          script: |
            const asset = await (await import("node:fs")).readFile("target/release/${github.repository.name}");

            await github.rest.repos.uploadReleaseAsset({
              url: ${{ needs.create-release.outputs.release-upload-url }},
              name: "lure-release-${{ runner.os }}",
              data: asset,
              headers: {
                'Content-Type': 'application/octet-stream',
                'Content-Length': asset.length
              }
            });
